package pl.poznan.put.cs.si.puttalky
 
import pl.poznan.put.cs.si.puttalky.Fakt;
import pl.poznan.put.cs.si.puttalky.Zamowienie; 
import pl.poznan.put.cs.si.puttalky.Ciasto;
import pl.poznan.put.cs.si.puttalky.Dodatek;
import pl.poznan.put.cs.si.puttalky.BazaWiedzy;
import java.util.Set;


/** Author: agalawrynowicz<br>
 * Date: 19-Dec-2016 */

rule "start"
	salience 3
	
	when
		not Fakt(nazwa=="start")
		zamowienie : Zamowienie()
	then
		zamowienie.powitanie();
		System.out.println();
		System.out.println();
		insert(new Fakt("start", "0"));
end

rule "Pytaj istniejaca pizze"
	salience 3

	when

		Fakt(nazwa == "start")
        not Fakt(nazwa == "gotowa_pizza")
        pizza : Pizza()
        parser : Parser()
        baza : BazaWiedzy()
	then
		  pizza.setMonit("Czy chcesz gotową pizze?:\n");
		  pizza.zadajPytanie();
		  parser.przetworzOdpowiedz();

		for (String slowo : parser.getSlowaKluczowe()){
			if(slowo.length()>2)
		        insert(new Fakt("gotowa_pizza", slowo.toLowerCase()));

		}

		//@TODO	brak dopasowania

end



rule "Podaj istniejaca pizze"
	salience 3

	when
		Fakt(nazwa == "gotowa_pizza", wartosc=="tak" ||  wartosc=="owszem"||  wartosc=="oczywiście"||  wartosc=="poproszę")
		not Fakt(nazwa == "pizza_propozycja")
		pizza : Pizza()
		parser : Parser()
		baza : BazaWiedzy()
	then

		  pizza.setMonit("Jaką gotową pizze podać?:\n");
		  pizza.zadajPytanie();
		  parser.przetworzOdpowiedz();

		for (String slowo : parser.getSlowaKluczowe()){
			for (String uriKlasy : baza.dopasujPizze(slowo)) {
		        insert(new Fakt("pizza_propozycja", uriKlasy));
		    }
		}

		//@TODO	brak dopasowania

end


rule "Podaj dodatki"
	salience 2
	
	when
		not Fakt(nazwa == "dodatek")
		not Fakt(nazwa == "pizza_propozycja")
		dodatek : Dodatek()
		parser : Parser()
		baza : BazaWiedzy()
	then
		  dodatek.setMonit("Jaki dodatek powinna zawierać Twoja pizza?:\n");
		  dodatek.zadajPytanie();
		  parser.przetworzOdpowiedz();
		String dodatki="";
		for (String slowo : parser.getSlowaKluczowe()){
			for (String uriKlasy : baza.dopasujDodatek(slowo)) {
			    dodatki=dodatki+uriKlasy+";";

		    } 
		}
		insert(new Fakt("dodatek", dodatki));
		    		
		//@TODO	brak dopasowania
		update(dodatek);
end

rule "Podaj rodzaj ciasta"
	salience 2
	
	when
		not Fakt(nazwa == "rodzaj_ciasta")
		ciasto : Ciasto()
		parser : Parser()
	then
		  ciasto.setMonit("Podaj rodzaj ciasta:\n");
		  ciasto.zadajPytanie();
		  parser.przetworzOdpowiedz();
		 
		for (String slowo : parser.getSlowaKluczowe()){
			if (slowo.equals("cienki")){
		       insert(new Fakt("rodzaj_ciasta", "cienkie"));
			} else if (slowo.equals("gruby")) {
		       insert(new Fakt("rodzaj_ciasta", "grube"));
			}
		}
					
		//@TODO	brak dopasowania
		
		update(ciasto);
end

rule "Polecana pizza"
	salience 1
	
	when
		Fakt(nazwa == "dodatek") && 
		Fakt(nazwa == "rodzaj_ciasta") && 	
		not Fakt(nazwa == "pizza_propozycja") &&
        $dodatek : Fakt( nazwa == "dodatek")
 		
		baza: BazaWiedzy()
		pizza: Pizza()
	then

		Set<String> pizze = baza.wyszukajPizzePoDodatkach($dodatek.getWartosc());
            
        if (pizze.size()>1){            		
			for (String nazwaPizzy : pizze) {
				insert(new Fakt("pizza_propozycja", nazwaPizzy));
		    	//System.out.println();
		    	if (!nazwaPizzy.equals("Nothing")){
		       	   System.out.println("Polecam pizzę:"+nazwaPizzy);
		       	}
		    }
		}
		else {
		    insert(new Fakt("pizza_propozycja", "Pizza Scpajcalna"));
		    String dodatki ="";
            for(String iri : baza.filtrujDodatki($dodatek.getWartosc())) {
                                        dodatki=dodatki+" "+baza.iriNaNazwe(iri);
                                    }
			System.out.println("Polecam pizzę spacjalną z dodatkiem "+ dodatki);
	    }

end


rule "zakończenie"

	when
		not (Fakt(nazwa == "koniec")) &&
		Fakt(nazwa == "pizza_propozycja") 

		zamowienie : Zamowienie()
	then
		insert(new Fakt("koniec", "0"));
		zamowienie.pozegnanie();
end

